create database logindata;
use logindata;
create table login (uname varchar(20),pass varchar(20));
insert into login values('DemoUserName1','DemoPassword1');
insert into login values('DemoUserName2','DemoPassword2');
insert into login values('DemoUserName3','DemoPassword3');
insert into login values('DemoUserName4','DemoPassword4');
insert into login values('DemoUserName5','DemoPassword5');
insert into login values('DemoUserName6','DemoPassword6');
insert into login values('DemoUserName7','DemoPassword7');
insert into login values('DemoUserName8','DemoPassword8');
insert into login values('DemoUserName9','DemoPassword9');
select * from login;